### ISSUE TITLE
Feature request: Change size

### ISSUE THREAD

**Issue by ChrisRomp** [Villhellm/lovelace-clock-card#2]
I'd like to be able to set the size of this, either by putting it in a constrained container (card) or explicitly setting its size in configuration.

Here it is today in a `horizontal-stack`:
![image](https://user-images.githubusercontent.com/1683889/88948624-01a01200-d247-11ea-9b85-ded5711d41af.png)

```yaml
 type: horizontal-stack
  cards:
    - type: custom:clock-card
      time_zone: "America/Los_Angeles"
    - type: custom:clock-card
      time_zone: "America/Los_Angeles"
```
